-- ============================================================================
-- DISABLE RLS ON EXISTING TABLES ONLY - NO ERRORS
-- ============================================================================

-- DISABLE RLS ON PROFILES TABLE
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;

-- DISABLE RLS ON BRAIDER_PROFILES TABLE
ALTER TABLE public.braider_profiles DISABLE ROW LEVEL SECURITY;

-- DISABLE RLS ON BOOKINGS TABLE
ALTER TABLE public.bookings DISABLE ROW LEVEL SECURITY;

-- DISABLE RLS ON PAYMENTS TABLE
ALTER TABLE public.payments DISABLE ROW LEVEL SECURITY;

-- DISABLE RLS ON MESSAGES TABLE (if exists)
DO $$ BEGIN
  ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- DISABLE RLS ON CONVERSATIONS TABLE (if exists)
DO $$ BEGIN
  ALTER TABLE public.conversations DISABLE ROW LEVEL SECURITY;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- DISABLE RLS ON SERVICES TABLE (if exists)
DO $$ BEGIN
  ALTER TABLE public.services DISABLE ROW LEVEL SECURITY;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- DISABLE RLS ON REVIEWS TABLE (if exists)
DO $$ BEGIN
  ALTER TABLE public.reviews DISABLE ROW LEVEL SECURITY;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- DISABLE RLS ON DISPUTES TABLE (if exists)
DO $$ BEGIN
  ALTER TABLE public.disputes DISABLE ROW LEVEL SECURITY;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- DISABLE RLS ON NOTIFICATIONS TABLE (if exists)
DO $$ BEGIN
  ALTER TABLE public.notifications DISABLE ROW LEVEL SECURITY;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;
