// Cities by state for Nigeria and USA

export const NIGERIAN_CITIES: Record<string, string[]> = {
  'Lagos': ['Ikeja', 'Victoria Island', 'Lekki', 'Ikoyi', 'Surulere', 'Yaba', 'Apapa', 'Badagry', 'Epe', 'Ikorodu', 'Lagos Island', 'Mushin', 'Ojo', 'Shomolu', 'Alimosho'],
  'Abuja': ['Garki', 'Wuse', 'Maitama', 'Asokoro', 'Gwarinpa', 'Kubwa', 'Nyanya', 'Karu', 'Lugbe', 'Jabi', 'Utako', 'Gudu', 'Apo', 'Bwari', 'Gwagwalada'],
  'Kano': ['Kano City', 'Fagge', 'Dala', 'Gwale', 'Kumbotso', 'Nassarawa', 'Tarauni', 'Ungogo', 'Dawakin Tofa', 'Gwarzo'],
  'Ibadan': ['Ibadan North', 'Ibadan South', 'Egbeda', 'Oluyole', 'Ona-Ara', 'Lagelu', 'Akinyele', 'Ido', 'Ibarapa', 'Oyo'],
  'Port Harcourt': ['Port Harcourt City', 'Obio-Akpor', 'Eleme', 'Ikwerre', 'Oyigbo', 'Tai', 'Gokana', 'Khana', 'Bonny', 'Degema'],
  'Enugu': ['Enugu City', 'Agbani', 'Awgu', 'Oji River', 'Udi', 'Igbo-Eze', 'Nsukka', 'Ezeagu', 'Nkanu'],
  'Benin City': ['Benin City', 'Oredo', 'Egor', 'Ikpoba-Okha', 'Ovia North-East', 'Ovia South-West', 'Orhionmwon', 'Uhunmwonde'],
  'Kaduna': ['Kaduna City', 'Zaria', 'Kafanchan', 'Soba', 'Kachia', 'Lere', 'Makarfi', 'Sabon Gari'],
  'Oyo': ['Ibadan', 'Ogbomosho', 'Oyo', 'Iseyin', 'Saki', 'Igboho', 'Kishi', 'Eruwa'],
  'Rivers': ['Port Harcourt', 'Obio-Akpor', 'Bonny', 'Degema', 'Eleme', 'Ikwerre', 'Oyigbo', 'Tai'],
  'Delta': ['Asaba', 'Warri', 'Sapele', 'Ughelli', 'Agbor', 'Abraka', 'Ozoro', 'Oleh'],
  'Anambra': ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia', 'Aguata', 'Ihiala', 'Ogidi', 'Agulu'],
  'Imo': ['Owerri', 'Orlu', 'Okigwe', 'Mbaise', 'Oguta', 'Ngor Okpala', 'Isu', 'Ideato'],
  'Abia': ['Umuahia', 'Aba', 'Ohafia', 'Arochukwu', 'Bende', 'Isuikwuato', 'Ukwa', 'Ugwunagbo'],
  'Cross River': ['Calabar', 'Ikom', 'Ogoja', 'Obudu', 'Akamkpa', 'Biase', 'Boki', 'Etung'],
  'Akwa Ibom': ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron', 'Abak', 'Etinan', 'Ini', 'Itu'],
  'Bayelsa': ['Yenagoa', 'Ogbia', 'Brass', 'Ekeremor', 'Kolokuma', 'Nembe', 'Sagbama', 'Southern Ijaw'],
  'Kwara': ['Ilorin', 'Offa', 'Omu-Aran', 'Lafiagi', 'Patigi', 'Kaiama', 'Baruten', 'Edu'],
  'Kogi': ['Lokoja', 'Okene', 'Kabba', 'Idah', 'Ankpa', 'Bassa', 'Dekina', 'Ibaji'],
  'Osun': ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede', 'Iwo', 'Ikirun', 'Ejigbo', 'Inisa'],
  'Ondo': ['Akure', 'Ondo City', 'Owo', 'Okitipupa', 'Ikare', 'Ifon', 'Ore', 'Idanre'],
  'Ekiti': ['Ado-Ekiti', 'Ikere-Ekiti', 'Ilawe-Ekiti', 'Ijero-Ekiti', 'Ise-Ekiti', 'Emure-Ekiti'],
  'Ogun': ['Abeokuta', 'Sagamu', 'Ijebu-Ode', 'Ota', 'Ilaro', 'Ifo', 'Ewekoro', 'Odeda'],
  'Nasarawa': ['Lafia', 'Keffi', 'Akwanga', 'Nasarawa', 'Doma', 'Keana', 'Obi', 'Wamba'],
  'Plateau': ['Jos', 'Bukuru', 'Shendam', 'Pankshin', 'Langtang', 'Wase', 'Kanam', 'Mangu'],
  'Niger': ['Minna', 'Bida', 'Suleja', 'Kontagora', 'Lapai', 'Agaie', 'Gbako', 'Gurara'],
  'Benue': ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala', 'Vandeikya', 'Ushongo', 'Gwer', 'Tarka'],
  'Taraba': ['Jalingo', 'Wukari', 'Bali', 'Gashaka', 'Gembu', 'Ibi', 'Karim Lamido', 'Lau'],
  'Adamawa': ['Yola', 'Mubi', 'Numan', 'Ganye', 'Gombi', 'Guyuk', 'Hong', 'Jada'],
  'Yobe': ['Damaturu', 'Potiskum', 'Gashua', 'Nguru', 'Bade', 'Bursari', 'Fika', 'Fune'],
  'Borno': ['Maiduguri', 'Biu', 'Gwoza', 'Chibok', 'Damboa', 'Dikwa', 'Gubio', 'Guzamala'],
  'Jigawa': ['Dutse', 'Hadejia', 'Gumel', 'Birnin Kudu', 'Kazaure', 'Ringim', 'Sule Tankarkar'],
  'Kebbi': ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru', 'Bagudo', 'Bunza', 'Dandi', 'Fakai'],
  'Sokoto': ['Sokoto City', 'Tambuwal', 'Bodinga', 'Dange-Shuni', 'Gada', 'Goronyo', 'Gudu'],
  'Zamfara': ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Anka', 'Bakura', 'Birnin Magaji', 'Bungudu'],
  'Gombe': ['Gombe City', 'Kaltungo', 'Billiri', 'Dukku', 'Funakaye', 'Kwami', 'Nafada'],
  'Bauchi': ['Bauchi City', 'Azare', 'Misau', 'Ningi', 'Alkaleri', 'Bogoro', 'Darazo', 'Dass'],
  'Gusau': ['Gusau', 'Kaura Namoda', 'Talata Mafara'],
  'Zaria': ['Zaria', 'Sabon Gari', 'Kwarbai', 'Tudun Wada'],
  'Calabar': ['Calabar Municipality', 'Calabar South', 'Akpabuyo', 'Bakassi', 'Biase'],
  'Katsina': ['Katsina City', 'Daura', 'Funtua', 'Malumfashi', 'Mashi', 'Musawa', 'Rimi'],
};

export const USA_CITIES: Record<string, string[]> = {
  'Alabama': ['Birmingham', 'Montgomery', 'Huntsville', 'Mobile', 'Tuscaloosa', 'Hoover', 'Dothan', 'Auburn'],
  'Alaska': ['Anchorage', 'Fairbanks', 'Juneau', 'Sitka', 'Ketchikan', 'Wasilla', 'Kenai', 'Kodiak'],
  'Arizona': ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale', 'Glendale', 'Gilbert', 'Tempe'],
  'Arkansas': ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro', 'North Little Rock', 'Conway'],
  'California': ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno', 'Sacramento', 'Long Beach', 'Oakland', 'Bakersfield', 'Anaheim', 'Santa Ana', 'Riverside', 'Stockton', 'Irvine', 'Chula Vista'],
  'Colorado': ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood', 'Thornton', 'Arvada', 'Westminster', 'Boulder'],
  'Connecticut': ['Bridgeport', 'New Haven', 'Hartford', 'Stamford', 'Waterbury', 'Norwalk', 'Danbury', 'New Britain'],
  'Delaware': ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Smyrna', 'Milford', 'Seaford', 'Georgetown'],
  'Florida': ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg', 'Hialeah', 'Tallahassee', 'Fort Lauderdale', 'Port St. Lucie', 'Cape Coral', 'Pembroke Pines', 'Hollywood', 'Gainesville', 'Miramar'],
  'Georgia': ['Atlanta', 'Augusta', 'Columbus', 'Macon', 'Savannah', 'Athens', 'Sandy Springs', 'Roswell', 'Johns Creek', 'Albany'],
  'Hawaii': ['Honolulu', 'Pearl City', 'Hilo', 'Kailua', 'Waipahu', 'Kaneohe', 'Mililani', 'Kahului'],
  'Idaho': ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Pocatello', 'Caldwell', 'Coeur d\'Alene', 'Twin Falls'],
  'Illinois': ['Chicago', 'Aurora', 'Joliet', 'Naperville', 'Rockford', 'Springfield', 'Elgin', 'Peoria', 'Champaign', 'Waukegan'],
  'Indiana': ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel', 'Fishers', 'Bloomington', 'Hammond'],
  'Iowa': ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City', 'Waterloo', 'Council Bluffs', 'Ames'],
  'Kansas': ['Wichita', 'Overland Park', 'Kansas City', 'Topeka', 'Olathe', 'Lawrence', 'Shawnee', 'Manhattan'],
  'Kentucky': ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington', 'Richmond', 'Georgetown', 'Florence'],
  'Louisiana': ['New Orleans', 'Baton Rouge', 'Shreveport', 'Metairie', 'Lafayette', 'Lake Charles', 'Kenner', 'Bossier City'],
  'Maine': ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn', 'Biddeford', 'Sanford', 'Augusta'],
  'Maryland': ['Baltimore', 'Frederick', 'Rockville', 'Gaithersburg', 'Bowie', 'Hagerstown', 'Annapolis', 'College Park'],
  'Massachusetts': ['Boston', 'Worcester', 'Springfield', 'Lowell', 'Cambridge', 'New Bedford', 'Brockton', 'Quincy', 'Lynn', 'Fall River'],
  'Michigan': ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor', 'Lansing', 'Flint', 'Dearborn', 'Livonia', 'Westland'],
  'Minnesota': ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth', 'Bloomington', 'Brooklyn Park', 'Plymouth', 'Saint Cloud'],
  'Mississippi': ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi', 'Meridian', 'Tupelo', 'Olive Branch'],
  'Missouri': ['Kansas City', 'Saint Louis', 'Springfield', 'Columbia', 'Independence', 'Lee\'s Summit', 'O\'Fallon', 'St. Joseph'],
  'Montana': ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Butte', 'Helena', 'Kalispell', 'Havre'],
  'Nebraska': ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney', 'Fremont', 'Hastings', 'Norfolk'],
  'Nevada': ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks', 'Carson City', 'Fernley', 'Elko'],
  'New Hampshire': ['Manchester', 'Nashua', 'Concord', 'Derry', 'Dover', 'Rochester', 'Salem', 'Merrimack'],
  'New Jersey': ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Edison', 'Woodbridge', 'Lakewood', 'Toms River', 'Hamilton', 'Trenton'],
  'New Mexico': ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell', 'Farmington', 'Clovis', 'Hobbs'],
  'New York': ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse', 'Albany', 'New Rochelle', 'Mount Vernon', 'Schenectady', 'Utica', 'Brooklyn', 'Queens', 'Manhattan', 'Bronx', 'Staten Island'],
  'North Carolina': ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem', 'Fayetteville', 'Cary', 'Wilmington', 'High Point', 'Concord'],
  'North Dakota': ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo', 'Williston', 'Dickinson', 'Mandan'],
  'Ohio': ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton', 'Parma', 'Canton', 'Youngstown', 'Lorain'],
  'Oklahoma': ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Lawton', 'Edmond', 'Moore', 'Midwest City'],
  'Oregon': ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro', 'Beaverton', 'Bend', 'Medford', 'Springfield'],
  'Pennsylvania': ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading', 'Scranton', 'Bethlehem', 'Lancaster', 'Harrisburg', 'Altoona'],
  'Rhode Island': ['Providence', 'Cranston', 'Warwick', 'Pawtucket', 'East Providence', 'Woonsocket', 'Coventry', 'Cumberland'],
  'South Carolina': ['Columbia', 'Charleston', 'North Charleston', 'Mount Pleasant', 'Rock Hill', 'Greenville', 'Summerville', 'Goose Creek'],
  'South Dakota': ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown', 'Mitchell', 'Yankton', 'Pierre'],
  'Tennessee': ['Memphis', 'Nashville', 'Knoxville', 'Chattanooga', 'Clarksville', 'Murfreesboro', 'Franklin', 'Jackson'],
  'Texas': ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso', 'Arlington', 'Corpus Christi', 'Plano', 'Laredo', 'Lubbock', 'Garland', 'Irving', 'Amarillo', 'Grand Prairie'],
  'Utah': ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem', 'Sandy', 'Ogden', 'St. George'],
  'Vermont': ['Burlington', 'South Burlington', 'Rutland', 'Barre', 'Montpelier', 'Winooski', 'St. Albans', 'Newport'],
  'Virginia': ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Newport News', 'Alexandria', 'Hampton', 'Roanoke', 'Portsmouth', 'Suffolk'],
  'Washington': ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue', 'Kent', 'Everett', 'Renton', 'Spokane Valley', 'Kirkland'],
  'West Virginia': ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Wheeling', 'Weirton', 'Fairmont', 'Martinsburg'],
  'Wisconsin': ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine', 'Appleton', 'Waukesha', 'Oshkosh', 'Eau Claire'],
  'Wyoming': ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs', 'Sheridan', 'Green River', 'Evanston'],
  'District of Columbia': ['Washington DC', 'Georgetown', 'Capitol Hill', 'Adams Morgan', 'Dupont Circle', 'Foggy Bottom'],
};

export function getCitiesForState(state: string, countryCode: 'NG' | 'US'): string[] {
  if (countryCode === 'NG') {
    return NIGERIAN_CITIES[state] || [];
  }
  return USA_CITIES[state] || [];
}
