// Nigerian States and Cities/Towns
export const NIGERIAN_STATES = {
  'Lagos': ['Lagos Island', 'Ikeja', 'Lekki', 'Victoria Island', 'Surulere', 'Yaba', 'Ikoyi', 'Ajah', 'Epe', 'Badagry'],
  'Abuja': ['Central Business District', 'Garki', 'Wuse', 'Maitama', 'Asokoro', 'Kubwa', 'Nyanya', 'Kuje'],
  'Kano': ['Kano City', 'Tarauni', 'Nassarawa', 'Gwale', 'Fagge', 'Dala', 'Ungogo'],
  'Rivers': ['Port Harcourt', 'Obio-Akpor', 'Eleme', 'Okrika', 'Bonny', 'Ogu-Bolo'],
  'Oyo': ['Ibadan', 'Ogbomoso', 'Oyo Town', 'Iseyin', 'Saki', 'Eruwa'],
  'Enugu': ['Enugu City', 'Nsukka', 'Udi', 'Agbani', 'Nkanu', 'Oji River'],
  'Anambra': ['Onitsha', 'Awka', 'Nnewi', 'Ekwulobia', 'Agulu', 'Ihiala'],
  'Edo': ['Benin City', 'Auchi', 'Ekpoma', 'Uromi', 'Irrua'],
  'Delta': ['Warri', 'Asaba', 'Sapele', 'Effurun', 'Agbor', 'Ughelli'],
  'Imo': ['Owerri', 'Orlu', 'Okigwe', 'Mbaise', 'Isiala-Mbano'],
  'Abia': ['Aba', 'Umuahia', 'Ohafia', 'Arochukwu', 'Bende'],
  'Bauchi': ['Bauchi City', 'Azare', 'Giade', 'Jama\'are'],
  'Borno': ['Maiduguri', 'Biu', 'Dikwa', 'Gwoza'],
  'Adamawa': ['Yola', 'Girei', 'Mubi', 'Numan', 'Guyuk'],
  'Taraba': ['Jalingo', 'Wukari', 'Takum', 'Zing'],
  'Plateau': ['Jos', 'Bukuru', 'Pankshin', 'Barkin Ladi', 'Vom'],
  'Nasarawa': ['Lafia', 'Keffi', 'Nasarawa', 'Akwanga'],
  'Kwara': ['Ilorin', 'Offa', 'Jebba', 'Pategi', 'Lafiagi'],
  'Niger': ['Minna', 'Suleja', 'Bida', 'Kontagora', 'Lapai'],
  'Kebbi': ['Birnin Kebbi', 'Argungu', 'Jega', 'Yauri'],
  'Sokoto': ['Sokoto City', 'Gusau', 'Tambuwal', 'Argungu'],
  'Katsina': ['Katsina City', 'Kankia', 'Daura', 'Funtua', 'Malumfashi'],
  'Zamfara': ['Gusau', 'Kaura Namoda', 'Talika', 'Anka'],
  'Jigawa': ['Dutse', 'Hadejia', 'Kazaure', 'Gumel', 'Birnin Kudu'],
  'Yobe': ['Damaturu', 'Potiskum', 'Gashua', 'Geidam'],
  'Cross River': ['Calabar', 'Ogoja', 'Ikom', 'Obudu'],
  'Akwa Ibom': ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron', 'Abak'],
  'Ebonyi': ['Abakaliki', 'Onueke', 'Afikpo', 'Ezza'],
  'Osun': ['Osogbo', 'Ilesha', 'Iwo', 'Ede', 'Ilesa'],
  'Ogun': ['Abeokuta', 'Ijebu-Ode', 'Sagamu', 'Ifo', 'Shagamu'],
  'Ekiti': ['Ado-Ekiti', 'Ikere', 'Ijero', 'Oye', 'Ilawe'],
  'Ondo': ['Akure', 'Ondo Town', 'Owo', 'Ile-Ife', 'Okitipupa'],
};

export const BRAIDING_SERVICES = [
  'Box Braids',
  'Cornrows',
  'Twists',
  'Locs',
  'Weaves',
  'Natural Hair Care',
  'Extensions',
  'Hair Coloring',
  'Relaxer Services',
  'Protective Styling',
  'Hair Treatment',
  'Wig Installation',
  'Crochet Braids',
  'Knotless Braids',
  'Goddess Braids',
  'Fulani Braids',
  'Micro Braids',
  'Senegalese Twists',
  'Marley Twists',
  'Faux Locs',
];

export const IDENTIFICATION_TYPES = [
  'National ID Card',
  'Passport',
  'Driver\'s License',
  'Voter\'s Card',
  'State ID',
  'International Passport',
];

export type NigerianState = keyof typeof NIGERIAN_STATES;
